"""
Denmark Tech Company Registry — 丹麦科技公司清单

数据来源:
  - Google Sheets: Denmark Tech Map
    https://docs.google.com/spreadsheets/d/18dz95Xji0AB35feTOPYuAw-13BLGABusWT3EsFzWyGc
  - Google My Maps
    https://www.google.com/mymaps/viewer?mid=1NAjLu7pBR_HEj6vXIYvpmct--K22UGU

用途:
  1. ScoutAgent 使用 career_url 批量抓取公司官网 Career 页面
  2. FilterAgent 使用 industry / description 判断公司是否匹配
  3. AnalystAgent 使用 glassdoor_score / values 作为分析上下文

数据结构:
  {
    "name": 公司名称,
    "address": 地址,
    "description": 简要描述,
    "homepage": 官网链接,
    "career_url": Career 页面链接 (核心字段),
    "employees": 员工数 (int or None),
    "industry": 行业类型,
    "glassdoor_score": Glassdoor 评分 (float or None),
    "avg_tenure": 平均任期 (float or None),
  }
"""

from __future__ import annotations

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Full Company Registry
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

DENMARK_TECH_COMPANIES: list[dict] = [
    # ── Tier 1: Large Enterprises with Active Tech Hiring ─────
    {
        "name": "A.P. Moller Maersk",
        "address": "Esplanaden 50, 1263 Copenhagen K",
        "description": "Global logistics and container shipping giant investing in digitalization, IoT, big data.",
        "homepage": "https://www.maersk.com/",
        "career_url": "https://www.maersk.com/careers",
        "employees": 100000,
        "industry": "Logistics",
        "glassdoor_score": 3.9,
        "avg_tenure": 3.3,
    },
    {
        "name": "Novo Nordisk",
        "address": "Novo Allé 1, 2880 Bagsværd",
        "description": "Leading healthcare company, diabetes care. Massive R&D, data science, AI in drug discovery.",
        "homepage": "https://www.novonordisk.com/",
        "career_url": "https://careers.novonordisk.com/",
        "employees": 80000,
        "industry": "Pharma",
        "glassdoor_score": 4.3,
        "avg_tenure": 3.2,
    },
    {
        "name": "Lego Group",
        "address": "Åstvej 1, 7190 Billund",
        "description": "Iconic toy manufacturer with expanding digital footprint, online retail, educational tech.",
        "homepage": "https://www.lego.com/",
        "career_url": "https://www.lego.com/da-dk/careers/search",
        "employees": 30000,
        "industry": "Retail",
        "glassdoor_score": 4.5,
        "avg_tenure": 3.6,
    },
    {
        "name": "Vestas Wind Systems",
        "address": "Hedeager 42, 8200 Aarhus N",
        "description": "Global leader in wind turbine manufacturing and sustainable energy solutions.",
        "homepage": "https://www.vestas.com/",
        "career_url": "https://careers.vestas.com/",
        "employees": 30000,
        "industry": "Energy",
        "glassdoor_score": 3.9,
        "avg_tenure": 4.0,
    },
    {
        "name": "Pandora",
        "address": "Havneholmen 17-19, 1561 Copenhagen V",
        "description": "International jewellery company, growing tech in e-commerce, data analytics, supply chain.",
        "homepage": "https://pandoragroup.com/",
        "career_url": "https://careers.pandoragroup.com/",
        "employees": 40000,
        "industry": "Retail",
        "glassdoor_score": 3.5,
        "avg_tenure": 2.8,
    },
    {
        "name": "Ørsted",
        "address": "Kraftværksvej 53, 7000 Fredericia",
        "description": "Global leader in offshore wind and renewable energy, advanced data analysis and smart grid.",
        "homepage": "https://orsted.com/",
        "career_url": "https://orsted.com/en/careers/open-positions",
        "employees": 8000,
        "industry": "Energy",
        "glassdoor_score": 3.8,
        "avg_tenure": 3.5,
    },
    {
        "name": "Carlsberg Group",
        "address": "J.C. Jacobsens Gade 1, 1799 Copenhagen V",
        "description": "Global brewing company using technology for production, supply chain, and data analytics.",
        "homepage": "https://www.carlsberggroup.com/",
        "career_url": "https://www.carlsberggroup.com/careers/",
        "employees": 40000,
        "industry": "FMCG",
        "glassdoor_score": 3.7,
        "avg_tenure": 3.0,
    },
    {
        "name": "ISS A/S",
        "address": "Buddingevej 197, 2860 Søborg",
        "description": "Global facility services company leveraging IoT and data analytics for smart buildings.",
        "homepage": "https://www.issworld.com/",
        "career_url": "https://www.issworld.com/en/careers",
        "employees": 350000,
        "industry": "Facility Services",
        "glassdoor_score": 3.5,
        "avg_tenure": 2.5,
    },
    {
        "name": "Danfoss",
        "address": "Pustervig 3, 1126 København K",
        "description": "Designs and manufactures products for cooling, heating, electrification, and power solutions.",
        "homepage": "https://www.danfoss.com/en/",
        "career_url": "https://jobs.danfoss.com/",
        "employees": 42000,
        "industry": "Industrial",
        "glassdoor_score": 3.9,
        "avg_tenure": 4.0,
    },
    {
        "name": "Grundfos",
        "address": "Martin Bachs Vej 3, 8850 Bjerringbro",
        "description": "Advanced pump systems and water solutions design, manufacture, and distribution.",
        "homepage": "https://www.grundfos.com/",
        "career_url": "https://www.grundfos.com/careers",
        "employees": 20000,
        "industry": "Industrial",
        "glassdoor_score": 4.0,
        "avg_tenure": 4.5,
    },
    {
        "name": "Siemens Gamesa Renewable Energy",
        "address": "Borupvej 16, 7330 Brande",
        "description": "Global leader in wind turbine manufacturing and renewable energy solutions.",
        "homepage": "https://www.siemensgamesa.com",
        "career_url": "https://www.siemensgamesa.com/en-int/careers",
        "employees": 27000,
        "industry": "Energy",
        "glassdoor_score": 3.6,
        "avg_tenure": 3.0,
    },

    # ── Tier 2: IT Consulting & Services ─────────────────────
    {
        "name": "Netcompany",
        "address": "Grønningen 17, 1270 Copenhagen K",
        "description": "IT consultancy providing end-to-end IT solutions for public and private sector.",
        "homepage": "https://www.netcompany.com/",
        "career_url": "https://netcompany.com/careers/",
        "employees": 8000,
        "industry": "Consulting",
        "glassdoor_score": 3.9,
        "avg_tenure": 2.8,
    },
    {
        "name": "Capgemini Danmark",
        "address": "Grønjordsvej 10, 2300 Copenhagen S",
        "description": "Global consultancy, technology services, and digital transformation.",
        "homepage": "https://www.capgemini.com/dk-da/",
        "career_url": "https://www.capgemini.com/dk-da/careers/",
        "employees": 350000,
        "industry": "Consulting",
        "glassdoor_score": 3.8,
        "avg_tenure": 3.0,
    },
    {
        "name": "Accenture Danmark",
        "address": "Arne Jacobsens Allé 15, 2300 Copenhagen S",
        "description": "Global professional services: strategy, consulting, digital, technology, operations.",
        "homepage": "https://www.accenture.com/dk-en",
        "career_url": "https://www.accenture.com/dk-en/careers",
        "employees": 700000,
        "industry": "Consulting",
        "glassdoor_score": 4.0,
        "avg_tenure": 2.5,
    },
    {
        "name": "Cognizant Denmark",
        "address": "Tuborg Boulevard 12, 2900 Hellerup",
        "description": "Global IT services and consulting.",
        "homepage": "https://www.cognizant.com/dk/en",
        "career_url": "https://careers.cognizant.com/global/en",
        "employees": 350000,
        "industry": "Consulting",
        "glassdoor_score": 3.7,
        "avg_tenure": 2.5,
    },
    {
        "name": "Tietoevry Denmark",
        "address": "Lautrupsgade 7, 2100 Copenhagen Ø",
        "description": "Nordic IT software and services company.",
        "homepage": "https://www.tietoevry.com/dk/",
        "career_url": "https://careers.tietoevry.com",
        "employees": None,
        "industry": "IT Services",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "NNIT",
        "address": "Østmarken 3A, 2860 Søborg",
        "description": "IT services provider for life sciences, finance, and public sector.",
        "homepage": "https://www.nnit.com/",
        "career_url": "https://www.nnit.com/career",
        "employees": None,
        "industry": "IT Services",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "KMD",
        "address": "Lautrupparken 40-42, 2750 Ballerup",
        "description": "Major Danish IT company providing software and IT solutions, primarily for public sector.",
        "homepage": "https://www.kmd.dk/",
        "career_url": None,
        "employees": None,
        "industry": "IT Services",
        "glassdoor_score": None,
        "avg_tenure": None,
    },

    # ── Tier 3: Big Tech in Denmark ──────────────────────────
    {
        "name": "Microsoft Denmark",
        "address": "Kanalvej 7, 2800 Kongens Lyngby",
        "description": "Software, cloud (Azure), hardware, AI R&D.",
        "homepage": "https://www.microsoft.com/da-dk/",
        "career_url": "https://careers.microsoft.com/v2/global/en/home.html",
        "employees": None,
        "industry": "Big Tech",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Google Denmark",
        "address": "Axel Towers, Axeltorv 2, 1609 Copenhagen V",
        "description": "Search, cloud, AI research, and sales. Also in Aarhus.",
        "homepage": "https://about.google/",
        "career_url": "https://www.google.com/about/careers/applications/",
        "employees": None,
        "industry": "Big Tech",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "IBM Danmark",
        "address": "Prøvensvej 1, 2610 Rødovre",
        "description": "IT services, cloud computing, AI solutions (Watson), enterprise software.",
        "homepage": "https://www.ibm.com/dk-en",
        "career_url": "https://www.ibm.com/careers",
        "employees": None,
        "industry": "Big Tech",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "SAP Danmark",
        "address": "Lautrupsgade 11, 2100 Copenhagen Ø",
        "description": "Enterprise software: ERP, CRM, cloud, data analytics.",
        "homepage": "https://www.sap.com/denmark/",
        "career_url": "https://jobs.sap.com",
        "employees": None,
        "industry": "Big Tech",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Oracle Danmark",
        "address": "Tuborg Boulevard 5, 2900 Hellerup",
        "description": "Database software, cloud systems, enterprise software.",
        "homepage": "https://www.oracle.com/dk/",
        "career_url": "https://www.oracle.com/europe/careers/",
        "employees": None,
        "industry": "Big Tech",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Salesforce Denmark",
        "address": "Arne Jacobsens Allé 13, 2300 Copenhagen S",
        "description": "Cloud-based CRM and enterprise cloud computing.",
        "homepage": "https://www.salesforce.com/dk/",
        "career_url": "https://www.salesforce.com/company/careers/",
        "employees": None,
        "industry": "Big Tech",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Unity Technologies Denmark",
        "address": "Niels Hemmingsens Gade 24, 1153 Copenhagen K",
        "description": "Leading platform for real-time 3D content, games, and experiences.",
        "homepage": "https://unity.com/",
        "career_url": None,
        "employees": None,
        "industry": "Gaming/3D",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Zendesk",
        "address": "Trommesalen 5, 1614 Copenhagen V",
        "description": "Customer service SaaS suite. Founded in Copenhagen.",
        "homepage": "https://www.zendesk.com/",
        "career_url": None,
        "employees": None,
        "industry": "SaaS",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Dynatrace Denmark",
        "address": "Lyskær 3CD, 2730 Herlev",
        "description": "AI-powered observability, application security, and AIOps.",
        "homepage": "https://www.dynatrace.com/",
        "career_url": "https://www.dynatrace.com/careers/",
        "employees": None,
        "industry": "SaaS",
        "glassdoor_score": None,
        "avg_tenure": None,
    },

    # ── Tier 4: SaaS & Scaleups (Active Hiring) ─────────────
    {
        "name": "Siteimprove",
        "address": "Sankt Annæ Plads 28, 1250 Copenhagen K",
        "description": "SaaS for website optimization: accessibility, SEO, content quality.",
        "homepage": "https://siteimprove.com/",
        "career_url": "https://careers.siteimprove.com/our-locations/",
        "employees": 500,
        "industry": "SaaS",
        "glassdoor_score": 2.7,
        "avg_tenure": 3.0,
    },
    {
        "name": "Trustpilot",
        "address": "Pilestræde 58, 1112 Copenhagen K",
        "description": "Global online review platform for consumers and businesses.",
        "homepage": "https://www.trustpilot.com/",
        "career_url": "https://business.trustpilot.com/jobs",
        "employees": 1200,
        "industry": "SaaS",
        "glassdoor_score": 4.0,
        "avg_tenure": 2.3,
    },
    {
        "name": "Templafy",
        "address": "Gærtorvet 1-5, 1799 Copenhagen V",
        "description": "SaaS for enterprise document creation, template management, content governance.",
        "homepage": "https://www.templafy.com/",
        "career_url": "https://www.templafy.com/home/about-us/careers/",
        "employees": None,
        "industry": "SaaS",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Penneo",
        "address": "Pilestræde 58, 1112 Copenhagen K",
        "description": "SaaS for digital signing, KYC/AML compliance, document workflow automation.",
        "homepage": "https://penneo.com/",
        "career_url": None,
        "employees": None,
        "industry": "SaaS",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Relewise",
        "address": "Vesterbrogade 149, 1620 Copenhagen V",
        "description": "AI-powered personalization platform for e-commerce: real-time recommendations and search.",
        "homepage": "https://relewise.com/",
        "career_url": None,
        "employees": None,
        "industry": "SaaS",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Keepit",
        "address": "Parken, Øster Allé 48, 2100 Copenhagen Ø",
        "description": "Cloud-to-cloud backup for M365, Google Workspace, Salesforce, Zendesk.",
        "homepage": "https://www.keepit.com/",
        "career_url": "https://careers.keepit.com/",
        "employees": None,
        "industry": "SaaS",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Konsolidator",
        "address": "Tobaksvejen 2A, 2860 Søborg",
        "description": "Cloud-based financial consolidation software.",
        "homepage": "https://konsolidator.com/",
        "career_url": None,
        "employees": None,
        "industry": "SaaS",
        "glassdoor_score": None,
        "avg_tenure": None,
    },

    # ── Tier 5: Fintech ──────────────────────────────────────
    {
        "name": "Pleo",
        "address": "Ravnsborg Tværgade 5C, 2200 Copenhagen N",
        "description": "Fintech unicorn: smart company cards and automated expense management.",
        "homepage": "https://www.pleo.io/",
        "career_url": "https://www.pleo.io/en/careers/jobs",
        "employees": 1000,
        "industry": "Finance",
        "glassdoor_score": 4.2,
        "avg_tenure": 2.2,
    },
    {
        "name": "Lunar",
        "address": "Hack Kampmanns Plads 10, 8000 Aarhus C",
        "description": "Nordic digital bank, mobile-first. Unicorn status.",
        "homepage": "https://www.lunar.app/",
        "career_url": "https://www.lunar.app/en/personal/jobs-and-career",
        "employees": 600,
        "industry": "Finance",
        "glassdoor_score": 3.4,
        "avg_tenure": 2.8,
    },
    {
        "name": "Danske Bank",
        "address": "Holmens Kanal 2-12, 1092 Copenhagen K",
        "description": "Major Danish bank: fintech, mobile banking, AI fraud detection, digital CX.",
        "homepage": "https://danskebank.com/",
        "career_url": "https://danskebank.com/careers",
        "employees": None,
        "industry": "Finance",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Nordea Bank (Danish Branch)",
        "address": "Grønjordsvej 10, 2300 Copenhagen S",
        "description": "Leading Nordic financial group: digital banking, mobile payments, fintech.",
        "homepage": "https://www.nordea.dk/",
        "career_url": "https://www.nordea.com/en/careers",
        "employees": None,
        "industry": "Finance",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Saxo Bank",
        "address": "Philip Heymans Alle 15, 2900 Hellerup",
        "description": "Danish bank specializing in online trading and investment. Fintech and regtech leader.",
        "homepage": "https://www.home.saxo/",
        "career_url": "https://www.home.saxo/about-us/careers",
        "employees": None,
        "industry": "Finance",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "SumUp",
        "address": "Vester Farimagsgade 19, 1606 København",
        "description": "Payment and business management solutions for SMEs and freelancers.",
        "homepage": "https://www.sumup.com/",
        "career_url": "https://www.sumup.com/careers/",
        "employees": None,
        "industry": "Finance",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Cardlay",
        "address": "Søndergade 2, 5000 Odense C",
        "description": "Fintech: white-label platform for corporate card solutions and expense management.",
        "homepage": "https://www.cardlay.com/",
        "career_url": None,
        "employees": None,
        "industry": "Finance",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Tradeshift",
        "address": "Njalsgade 21F, 2300 Copenhagen S",
        "description": "Cloud-based business network for supply chain payments. Danish unicorn.",
        "homepage": "https://tradeshift.com/",
        "career_url": None,
        "employees": None,
        "industry": "Finance",
        "glassdoor_score": None,
        "avg_tenure": None,
    },

    # ── Tier 6: AI & Deep Tech ───────────────────────────────
    {
        "name": "Synthesia",
        "address": "Studiestræde 35, 1455 Copenhagen K",
        "description": "AI video generation platform with AI avatars and voiceovers. Unicorn.",
        "homepage": "https://www.synthesia.io/",
        "career_url": "https://www.synthesia.io/careers",
        "employees": None,
        "industry": "AI",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Corti",
        "address": "Købmagergade 60, 1150 Copenhagen K",
        "description": "AI for medical professionals: analyzing patient consultations, detecting critical illness.",
        "homepage": "https://www.corti.ai/",
        "career_url": "https://www.corti.ai/careers",
        "employees": None,
        "industry": "AI/HealthTech",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "2021.AI",
        "address": "Njalsgade 19D, 2300 Copenhagen S",
        "description": "AI platform (Grace) for implementing and scaling AI with governance and responsible AI.",
        "homepage": "https://www.2021.ai/",
        "career_url": None,
        "employees": None,
        "industry": "AI",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Abzu",
        "address": "Studiestræde 35, 1455 Copenhagen K",
        "description": "Explainable AI (XAI) technology: QLattice for transparent AI models.",
        "homepage": "https://abzu.ai/",
        "career_url": "https://www.abzu.ai/about-us/careers/",
        "employees": None,
        "industry": "AI",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Silo AI (Denmark)",
        "address": "Njalsgade 19C, 2300 Copenhagen S",
        "description": "One of the largest private AI labs in the Nordics.",
        "homepage": "https://www.silo.ai/",
        "career_url": None,
        "employees": None,
        "industry": "AI",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Uizard Technologies",
        "address": "Titangade 11, 2200 Copenhagen N",
        "description": "AI-powered design tool: generate UI designs from text prompts or sketches.",
        "homepage": "https://uizard.io/",
        "career_url": "https://uizard.io/careers/",
        "employees": None,
        "industry": "AI",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Raffle.ai",
        "address": "Artillerivej 86, 2300 Copenhagen S",
        "description": "AI-powered knowledge discovery and sharing platform.",
        "homepage": "https://www.raffle.ai/",
        "career_url": "https://raffle.ai/career",
        "employees": None,
        "industry": "AI",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Go Autonomous",
        "address": "Symbion, Fruebjergvej 3, 2100 Copenhagen Ø",
        "description": "AI-powered B2B sales order processing automation.",
        "homepage": "https://www.goautonomous.io/",
        "career_url": "https://goautonomous.io/careers/",
        "employees": None,
        "industry": "AI",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Certainly",
        "address": "Købmagergade 3, 1150 Copenhagen K",
        "description": "AI-powered chatbot platform for customer service and e-commerce.",
        "homepage": "https://www.certainly.io/",
        "career_url": None,
        "employees": None,
        "industry": "AI",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Cerebriu",
        "address": "Ole Maaløes Vej 3, 2200 København N",
        "description": "HealthTech AI: automating workflows for brain MRI diagnostics.",
        "homepage": "https://cerebriu.com/",
        "career_url": None,
        "employees": None,
        "industry": "AI/HealthTech",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Heyhack",
        "address": "Fruebjergvej 3, 2100 København Ø",
        "description": "Automated penetration testing platform. AI cybersecurity startup.",
        "homepage": "https://heyhack.com/",
        "career_url": None,
        "employees": None,
        "industry": "AI/Cybersecurity",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "GetWhy",
        "address": "Sundkaj 125, 2150 København",
        "description": "AI-powered consumer insights: uncover hidden stories at survey speed.",
        "homepage": "https://www.getwhy.io/",
        "career_url": None,
        "employees": None,
        "industry": "AI",
        "glassdoor_score": None,
        "avg_tenure": None,
    },

    # ── Tier 7: Robotics & Hardware ──────────────────────────
    {
        "name": "Universal Robots",
        "address": "Energivej 25, 5260 Odense S",
        "description": "Leading manufacturer of collaborative robots (cobots). Part of Teradyne.",
        "homepage": "https://www.universal-robots.com/",
        "career_url": "https://www.universal-robots.com/about-us/careers/",
        "employees": None,
        "industry": "Robotics",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Mobile Industrial Robots (MiR)",
        "address": "Emil Neckelmanns Vej 15F, 5220 Odense SØ",
        "description": "Autonomous mobile robots (AMRs) for logistics automation. Part of Teradyne.",
        "homepage": "https://www.mobile-industrial-robots.com/",
        "career_url": "https://mobile-industrial-robots.com/about/career",
        "employees": None,
        "industry": "Robotics",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Blue Ocean Robotics",
        "address": "Svendborgvej 226, 5260 Odense S",
        "description": "Professional service robots across sectors.",
        "homepage": "https://www.blue-ocean-robotics.com/",
        "career_url": "https://www.blue-ocean-robotics.com/career",
        "employees": None,
        "industry": "Robotics",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "3Shape",
        "address": "Holmens Kanal 7, 1060 Copenhagen K",
        "description": "3D scanners and CAD/CAM software for dental and audiology.",
        "homepage": "https://www.3shape.com/",
        "career_url": "https://www.3shape.com/about-us/careers",
        "employees": None,
        "industry": "MedTech",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "GN Store Nord (Jabra, GN Hearing)",
        "address": "Lautrupbjerg 7, 2750 Ballerup",
        "description": "Intelligent audio solutions, headphones, hearing aids. Significant R&D.",
        "homepage": "https://www.gn.com/",
        "career_url": "https://gn.wd3.myworkdayjobs.com/GN-Careers",
        "employees": None,
        "industry": "Audio/MedTech",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Bang & Olufsen",
        "address": "Bang og Olufsen Allé 1, 7600 Struer",
        "description": "Luxury audio-visual brand: high-end speakers, headphones, televisions.",
        "homepage": "https://www.bang-olufsen.com/",
        "career_url": None,
        "employees": None,
        "industry": "Audio",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Demant (Oticon, EPOS)",
        "address": "Kongebakken 9, 2765 Smørum",
        "description": "Global hearing healthcare and audio tech: Oticon hearing aids, EPOS audio.",
        "homepage": "https://www.demant.com/",
        "career_url": "https://careers.demant.com",
        "employees": None,
        "industry": "MedTech",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "TrackMan",
        "address": "Stamholmen 110, 2650 Hvidovre",
        "description": "Sports tracking technology: radar and camera systems for golf, baseball.",
        "homepage": "https://trackmangolf.com/",
        "career_url": "https://www.trackman.com/careers",
        "employees": None,
        "industry": "SportsTech",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Napatech",
        "address": "Tobaksvejen 23A, 2860 Søborg",
        "description": "High-performance SmartNICs for network monitoring and cybersecurity.",
        "homepage": "https://www.napatech.com/",
        "career_url": None,
        "employees": None,
        "industry": "Hardware",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "ATLANT 3D Nanosystems",
        "address": "Diplomvej 381, 2800 Kongens Lyngby (DTU Science Park)",
        "description": "Deep tech: atomic layer 3D printing of micro and nanodevices.",
        "homepage": "https://atlant3d.com/",
        "career_url": "https://atlant3d.com/careers/",
        "employees": None,
        "industry": "Deep Tech",
        "glassdoor_score": None,
        "avg_tenure": None,
    },

    # ── Tier 8: Other Scaleups & Startups ────────────────────
    {
        "name": "Too Good To Go",
        "address": "Landskronagade 66, 2100 Copenhagen Ø",
        "description": "Social impact app connecting users with surplus food to combat waste.",
        "homepage": "https://www.toogoodtogo.com/",
        "career_url": None,
        "employees": None,
        "industry": "Social Impact",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Veo Technologies",
        "address": "Aldersrogade 6C, 2100 Copenhagen Ø",
        "description": "AI-powered sports camera and analytics platform.",
        "homepage": "https://veo.co/",
        "career_url": "https://www.veo.co/careers",
        "employees": None,
        "industry": "SportsTech",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Dixa",
        "address": "Vimmelskaftet 41A, 1161 Copenhagen K",
        "description": "Unified customer service platform: email, chat, messaging, phone.",
        "homepage": "https://www.dixa.com/",
        "career_url": "https://www.dixa.com/careers",
        "employees": None,
        "industry": "SaaS",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Planday (Xero)",
        "address": "Njalsgade 17A, 2300 Copenhagen S",
        "description": "Workforce management: scheduling, time tracking, payroll integration.",
        "homepage": "https://www.planday.com/",
        "career_url": "https://www.planday.com/careers",
        "employees": None,
        "industry": "SaaS",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Chainalysis (Danish office)",
        "address": "Njalsgade 76, 2300 Copenhagen S",
        "description": "Blockchain analysis for government agencies, exchanges, financial institutions.",
        "homepage": "https://www.chainalysis.com/",
        "career_url": "https://www.chainalysis.com/careers/",
        "employees": None,
        "industry": "Blockchain",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Labster",
        "address": "Carl Jacobsens Vej 16, 2500 Valby",
        "description": "Virtual laboratory simulations for STEM education.",
        "homepage": "https://www.labster.com/",
        "career_url": "https://www.labster.com/careers",
        "employees": None,
        "industry": "EdTech",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Lenus eHealth",
        "address": "Rued Langgaards Vej 8, 2300 Copenhagen S",
        "description": "All-in-one platform for online coaches and fitness professionals.",
        "homepage": "https://lenus.io/",
        "career_url": "https://www.lenusehealth.com/careers",
        "employees": None,
        "industry": "HealthTech",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Podimo",
        "address": "Gasværksvej 48, 1756 Copenhagen V",
        "description": "Subscription service for podcasts and audiobooks with exclusive content.",
        "homepage": "https://podimo.com/",
        "career_url": "https://careers.podimo.com",
        "employees": None,
        "industry": "Media",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Monta",
        "address": "Njalsgade 21G, 2300 Copenhagen S",
        "description": "EV charging ecosystem operating platform. Rapidly growing scaleup.",
        "homepage": "https://monta.com/",
        "career_url": "https://careers.monta.com/",
        "employees": None,
        "industry": "GreenTech",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Airtame",
        "address": "Kuglegårdsvej 1, 1434 Copenhagen K",
        "description": "Wireless screen sharing and digital signage solutions.",
        "homepage": "https://airtame.com/",
        "career_url": "https://airtame.com/careers",
        "employees": None,
        "industry": "Hardware",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Worksome",
        "address": "Njalsgade 19C, 2300 Copenhagen S",
        "description": "Platform for managing external workforce: freelancers, contractors, payments.",
        "homepage": "https://www.worksome.com/",
        "career_url": "https://www.worksome.com/career",
        "employees": None,
        "industry": "HR Tech",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Agreena",
        "address": "Ny Carlsberg Vej 80, 1799 Copenhagen V",
        "description": "Agritech: soil carbon certification for regenerative agriculture.",
        "homepage": "https://agreena.com/",
        "career_url": None,
        "employees": None,
        "industry": "AgriTech",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Dreamdata",
        "address": "Skindergade 3, 1159 Copenhagen K",
        "description": "B2B revenue attribution and analytics platform.",
        "homepage": "https://dreamdata.io/",
        "career_url": None,
        "employees": None,
        "industry": "SaaS",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Vivino",
        "address": "Njalsgade 21G, 2300 København",
        "description": "Global online wine marketplace and app.",
        "homepage": "https://www.vivino.com/",
        "career_url": "https://careers.vivino.com",
        "employees": None,
        "industry": "Marketplace",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Mouseflow",
        "address": "Flæsketorvet 68, 1711 København",
        "description": "Website user behavior analytics: session replays, heatmaps, funnels.",
        "homepage": "https://mouseflow.com/",
        "career_url": None,
        "employees": None,
        "industry": "SaaS",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Matterport (EMEA HQ)",
        "address": "Gladsaxe Møllevej 26, 2860 Søborg",
        "description": "3D data platform to create digital twins of physical spaces.",
        "homepage": "https://matterport.com/",
        "career_url": None,
        "employees": None,
        "industry": "3D Tech",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "ZeroNorth",
        "address": "Strandvejen 100, 2900 Hellerup",
        "description": "Shipping tech: AI and data analytics to optimize voyages, reduce emissions.",
        "homepage": "https://zeronorth.com/",
        "career_url": "https://zeronorth.com/careers",
        "employees": None,
        "industry": "GreenTech",
        "glassdoor_score": None,
        "avg_tenure": None,
    },

    # ── Tier 9: Software & Enterprise ────────────────────────
    {
        "name": "SimCorp",
        "address": "Weidekampsgade 16, 2300 Copenhagen S",
        "description": "Integrated investment management solutions for global financial services.",
        "homepage": "https://www.simcorp.com/",
        "career_url": "https://www.simcorp.com/About-Us/Career",
        "employees": None,
        "industry": "FinTech",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Systematic",
        "address": "Søren Frichs Vej 39, 8000 Aarhus C",
        "description": "Complex software for defense, healthcare, library & learning, citizen services.",
        "homepage": "https://systematic.com/",
        "career_url": "https://systematic.com/int/careers/",
        "employees": None,
        "industry": "Defense/Gov",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Milestone Systems",
        "address": "Banemarksvej 50, 2605 Brøndby",
        "description": "Global leader in open platform IP video management software.",
        "homepage": "https://www.milestonesys.com/",
        "career_url": None,
        "employees": None,
        "industry": "Security",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "cBrain",
        "address": "Nørre Voldgade 9, 1358 Copenhagen K",
        "description": "Government process management software (F2).",
        "homepage": "https://www.cbrain.com/",
        "career_url": "https://www.cbrain.com/company/careers",
        "employees": None,
        "industry": "GovTech",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Configit",
        "address": "Amerika Plads 37, 2100 Copenhagen Ø",
        "description": "Configuration Lifecycle Management (CLM) software for manufacturing.",
        "homepage": "https://configit.com/",
        "career_url": None,
        "employees": None,
        "industry": "Software",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Area9 Lyceum",
        "address": "Strandvejen 100, 2900 Hellerup",
        "description": "Adaptive learning platforms and AI-driven educational technology.",
        "homepage": "https://area9lyceum.com/",
        "career_url": None,
        "employees": None,
        "industry": "EdTech",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "CluedIn",
        "address": "Titangade 11, 2200 Copenhagen N",
        "description": "Master Data Management (MDM) using knowledge graphs.",
        "homepage": "https://www.cluedin.com/",
        "career_url": "https://www.cluedin.com/careers",
        "employees": None,
        "industry": "Data",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "OpenLi",
        "address": "Gothersgade 8B, 1123 Copenhagen K",
        "description": "Privacy-tech SaaS for automated GDPR/ePrivacy compliance.",
        "homepage": "https://www.openli.com/",
        "career_url": None,
        "employees": None,
        "industry": "Privacy",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Kamstrup",
        "address": "Gl Struervej 44, 7500 Holstebro",
        "description": "Intelligent metering solutions for energy and water utilities.",
        "homepage": "https://www.kamstrup.com/",
        "career_url": None,
        "employees": None,
        "industry": "GreenTech",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Hedia",
        "address": "Sortedam Dossering 55A, 2100 Copenhagen Ø",
        "description": "Digital health: AI-powered diabetes management app.",
        "homepage": "https://hedia.co/",
        "career_url": None,
        "employees": None,
        "industry": "HealthTech",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
    {
        "name": "Valuer.ai",
        "address": "Njalsgade 19D, 2300 Copenhagen S",
        "description": "AI-powered platform for discovering startups and innovative technologies.",
        "homepage": "https://valuer.ai/",
        "career_url": "https://valuer.ai/careers",
        "employees": None,
        "industry": "AI",
        "glassdoor_score": None,
        "avg_tenure": None,
    },
]


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Helper Functions
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


def get_companies_with_career_urls() -> list[dict]:
    """只返回有 career_url 的公司 — 可直接用于 scrape_company_careers"""
    return [c for c in DENMARK_TECH_COMPANIES if c.get("career_url")]


def get_companies_by_industry(industry: str) -> list[dict]:
    """按行业筛选公司"""
    return [
        c for c in DENMARK_TECH_COMPANIES
        if c.get("industry", "").lower() == industry.lower()
    ]


def get_top_rated_companies(min_score: float = 4.0) -> list[dict]:
    """获取 Glassdoor 高评分公司"""
    return [
        c for c in DENMARK_TECH_COMPANIES
        if c.get("glassdoor_score") and c["glassdoor_score"] >= min_score
    ]


def get_all_career_urls() -> dict[str, str]:
    """获取 {公司名: career_url} 映射"""
    return {
        c["name"]: c["career_url"]
        for c in DENMARK_TECH_COMPANIES
        if c.get("career_url")
    }


def get_company_names() -> list[str]:
    """获取所有公司名列表"""
    return [c["name"] for c in DENMARK_TECH_COMPANIES]


def print_summary():
    """打印公司清单摘要"""
    total = len(DENMARK_TECH_COMPANIES)
    with_career = len(get_companies_with_career_urls())
    with_glassdoor = len([c for c in DENMARK_TECH_COMPANIES if c.get("glassdoor_score")])
    industries = set(c.get("industry", "Unknown") for c in DENMARK_TECH_COMPANIES)

    print(f"\n📊 Denmark Tech Company Registry")
    print(f"   Total companies: {total}")
    print(f"   With career URL: {with_career}")
    print(f"   With Glassdoor:  {with_glassdoor}")
    print(f"   Industries ({len(industries)}): {', '.join(sorted(industries))}")
    print()

    # Top rated
    top = get_top_rated_companies(4.0)
    if top:
        print("   ⭐ Top Glassdoor (≥4.0):")
        for c in sorted(top, key=lambda x: x["glassdoor_score"], reverse=True):
            print(f"      {c['glassdoor_score']:.1f} - {c['name']}")
    print()


if __name__ == "__main__":
    print_summary()
